[pytest]
addopts = -q --cov=app --cov-report=term-missing --cov-fail-under=100
pythonpath = .
testpaths = tests
filterwarnings =
	ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
